### Importing Numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

### Array in Numpy

* NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.
* Why use NumPy?

* NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### Creating an array

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1])

[4 5 6]


### Creating array of zeros and ones

In [5]:
b=np.zeros(2)
print("Array of 0's",b)
 
c=np.ones(2)
print("Array of 0's",c)

Array of 0's [0. 0.]
Array of 0's [1. 1.]


### Creating empty array-numbers are random

In [6]:
d=np.empty(4)
print("Random numbers:",d)

Random numbers: [1.40392898e-311 6.01346953e-154 4.72159844e+257 1.12320239e+219]


### Array with a range of elementss
And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size

In [7]:
e=np.array(range(4))
print(e)


f=np.array(range(1,12,3))
print(f)

[0 1 2 3]
[ 1  4  7 10]


 ### Specifying data type
While the default data type is floating point (np.float64),you can explicitly specify which data type you want using the dtype keyword.

In [8]:
g=np.ones(2,dtype=np.int64)
print(g)

[1 1]


### Sorting, contatination of arrays

In [9]:
h=np.array([2,7,4,5,12,9,10])
np.sort(h)

array([ 2,  4,  5,  7,  9, 10, 12])

In [10]:
i = np.array([1, 2, 3, 4])
j = np.array([5, 6, 7, 8])
np.concatenate((i,j))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6]])
a3=np.concatenate((a1,a2), axis=0)
print(a3)

[[1 2]
 [3 4]
 [5 6]]


### Dimensions of the array

In [12]:
a3.ndim

2

### Shape of the array

In [13]:
a4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a4.shape

(2, 5)

### Total number of elements in the array

In [14]:
a3.size

6

### Reshaping the array

In [15]:
a4=np.arange(8)
a4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
a5=a4.reshape(2,4)
print(a5)

[[0 1 2 3]
 [4 5 6 7]]


### Indexing and Slicing

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step]

In [17]:
data=np.array([1,2,3,4,5,6,7])
print("Extracts the specified index",data[1])
print("Starting from index 0 till 2-1:",data[0:2])
print("Starting from index 1 till the very end of array:",data[1:])

Extracts the specified index 2
Starting from index 0 till 2-1: [1 2]
Starting from index 1 till the very end of array: [2 3 4 5 6 7]


In [18]:
print(data[4:])
print(data[:4])

[5 6 7]
[1 2 3 4]


* Slice from the index 3 from the end to index 1 from the end:

In [19]:
print(data[-3:-1])

[5 6]


From the second element, slice elements from index 1 to index 4 (not included)

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

[7 8 9]


In [21]:
arr1=np.array([[10,20,30,200,300,400,500],[40,50,60,70,80,90,100]])
print(arr1[1,1:5])
print(arr1[0,4:])
print(arr1[0:2,3:])
print(arr1[0:,1:4])
print(arr1[0:,-2])

[50 60 70 80]
[300 400 500]
[[200 300 400 500]
 [ 70  80  90 100]]
[[ 20  30 200]
 [ 50  60  70]]
[400  90]


### Axis
* Axis=0 Cloumn
* Axis=1 Row

In [22]:
arr2=np.array([[1,3,2,4],[8,6,5,9],[6,4,5,2]])
print(arr2)
m=np.sort(arr2,axis=0)
print(m)

[[1 3 2 4]
 [8 6 5 9]
 [6 4 5 2]]
[[1 3 2 2]
 [6 4 5 4]
 [8 6 5 9]]


### Arithematic Operator

In [23]:
a=np.array([[1,2],[4,5]])
b=np.array([[3,5],[3,6]])
print(a)
print(b)
print("Sum of Array:",a+b)
print("Product of Array:",a*b)
print("Product of Array:", a.dot(b))

[[1 2]
 [4 5]]
[[3 5]
 [3 6]]
Sum of Array: [[ 4  7]
 [ 7 11]]
Product of Array: [[ 3 10]
 [12 30]]
Product of Array: [[ 9 17]
 [27 50]]


## Linear Algebra

### Transpose of Matrix

In [24]:
mat=np.array([[1,2,5],[3,4,6]])
print(mat)
print("Transpose of matrix:",np.transpose(mat))

[[1 2 5]
 [3 4 6]]
Transpose of matrix: [[1 3]
 [2 4]
 [5 6]]


### Determinant of a Matrix

In [25]:
mat1=np.array(([1,3,1],[2,7,11],[3,5,2]))
print(mat1)
print("Determinant of this matrix")
print(np.linalg.det(mat1))

[[ 1  3  1]
 [ 2  7 11]
 [ 3  5  2]]
Determinant of this matrix
35.00000000000001


### Inverse of a Matrix

In [26]:
m = np.array([[1,2],[3,4]])
print(m)
print("Inverse of matrix:")
print(np.linalg.inv(m))

[[1 2]
 [3 4]]
Inverse of matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Rank of Matrix

In [28]:
n = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print("Rank of matrix:",np.linalg.matrix_rank(n))

Rank of matrix: 3


### Eigen Function

**numpy.linalg.eigh(a, UPLO=’L’)**

This function is used to return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.Returns two objects, a 1-D array containing the eigenvalues of a, and a 2-D square array or matrix (depending on the input type) of the corresponding eigenvectors (in columns).

In [31]:
n1 = np.array([[1, -2j], [2j, 5]])
print(n1)
c,d=np.linalg.eigh(n1)
print("Eigen value is:  ",c)
print("Eigen value is:  ",d)

[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is:   [0.17157288 5.82842712]
Eigen value is:   [[-0.92387953-0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


**numpy.linalg.eig(a) :**
his function is used to compute the eigenvalues and right eigenvectors of a square array.

In [32]:
n2 = np.diag((1, 2, 3))
c,d=np.linalg.eig(n2)
print("Eigen value is:  ",c)
print("Eigen value is:  ",d)

Eigen value is:   [1. 2. 3.]
Eigen value is:   [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
